name: Terraform Enterprise Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: gcplearning-15042026
  PROJECT_NUMBER: 177707171764
  REGION: asia-south1

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-dev/providers/github
          service_account: terraform-dev-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=terraform-state-gcplearning" \
            -backend-config="prefix=dev"

      - name: Terraform Plan
        run: terraform plan -var="environment=dev"

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-dev/providers/github
          service_account: terraform-dev-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=terraform-state-gcplearning" \
            -backend-config="prefix=dev"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=dev"